### PR TITLE
Update terminology

### PR DESCRIPTION
**Pull request by qiujian16**
- One-line PR description:

- Issue link:

- Other comments:

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
lgtm

**Comment by RainbowMango** [comment]
> For instance, workload distribution tools like GitOps or [Work API] (https://github.com/kubernetes-sigs/work-api) can leverage this API to make informed decisions about which cluster is best suited to handle a particular workload.

Just found a broken link in chapter [strory-1](https://github.com/qiujian16/k8s-enhancements/tree/cluster-inventory/keps/sig-multicluster/cluster-inventory#story-1-multicluster-workload-distribution).

> Nn immutable field set by a cluster manager when this cluster resources is created by it. Each cluster manager instance should set a different values to this field

`Nn` A typo? in the chapter [Cluster Manager](https://github.com/qiujian16/k8s-enhancements/tree/cluster-inventory/keps/sig-multicluster/cluster-inventory#cluster-manager).

> Predefined condition types:

After going through the API Example I can see that there are 3 predefined condition types:
- ControlPlaneHealthy 
- AllNodesHealthy 
- Joined

But the description of [Conditions](https://github.com/qiujian16/k8s-enhancements/tree/cluster-inventory/keps/sig-multicluster/cluster-inventory#conditions), is a little bit misleading in that there is a condition `Healthy`. No big deal though.

> Joined: indicate the cluster is under management by the control plane. The status of the cluster SHOULD be updated by the controlplane under this condition.

I don't quite understand the meaning of `Joined` condition.  Which `control plane` we are talking about here? Is it the `Cluster Manger`?

**Comment by qiujian16** [comment]
< I don't quite understand the meaning of Joined condition. Which control plane we are talking about here? Is it the Cluster Manger?

yes it is cluster manager. Updated to cluster manager

< But the description of [Conditions](https://github.com/qiujian16/k8s-enhancements/tree/cluster-inventory/keps/sig-multicluster/cluster-inventory#conditions), is a little bit misleading in that there is a condition Healthy. No big deal though.

changed a little bit wording here.


the updated PR https://github.com/qiujian16/k8s-enhancements/pull/4

**Comment by RainbowMango** [comment]
One more thing that I wanted to talk about a long time ago, it's about the `terminology` of the cluster managed by a `Cluster Manager`.

I see you used `spoke cluster` several times in this proposal, I think it's not a standard name, cluster managers name it differently:
- For kubefed, it names the cluster with `member cluster`, see the [userguide](https://github.com/kubernetes-retired/kubefed/blob/master/docs/userguide.md#verifying-api-type-is-installed-on-all-member-clusters) for reference.
- For Karmada, it names the cluster with `member cluster`, inherits from Kubefed.
- For OCM, it names the cluster with `spoke cluster`, 
- For Clusternet, it names the cluster with `child cluster`, see the [documentation](https://clusternet.io/docs/quick-start/) for reference.
- For Fleet manager, it names the cluster with `member cluster`, see the [documentation](https://azure.microsoft.com/en-us/products/kubernetes-fleet-manager) for reference.

In my opinion, each cluster manager can decide the terminology in their project, but in the context of Kubernetes Sig-multicluster, we'd better use `member cluster` as that is the terminology the SIG already used for a long time(just to make communication easier and avoid confusion caused by new terminologies).

What do you think?

**Pull request merged**
